query GetAccountBalance($account: String!) {
  getAccountBalance(account: $account) {
    pending_hbd_unstaking
    consensus_unstaking
    hbd
    hbd_savings
    hive_consensus
    hive
  }
  getAccountRC(account: $account) {
    amount
  }
}