query GetTransactions($did: String, $limit: Int, $offset: Int) {
	findLedgerTXs(filterOptions: { limit: $limit, offset: $offset, byToFrom: $did }) @paginate {
		id
		amount
		block_height
		timestamp
		from
		owner
		type
		asset
		tx_id
	}
}
